{
    "port": 9001,
    "server_name": "potato annotator",
    "annotation_task_name": "Intimacy likert",
    "output_annotation_dir": "projects/multilingual-tweet-intimacy/annotation_output/pilot/Chinese/",
    "output_annotation_format": "tsv",
    "annotation_codebook_url": "",
    "data_files": [
        "projects/multilingual-tweet-intimacy/data_files/likert_pilot_100_Chinese.jsonl"
    ],
    "item_properties": {
        "id_key": "id",
        "text_key": "text"
    },
    "list_as_text": {
        "text_list_prefix_type": "alphabet"
    },
    "user_config": {
        "allow_all_users": true,
        "users": []
    },
    "require_no_password": true,
    "jumping_to_id_disabled": true,
    "hide_navbar": true,
    "surveyflow": {
        "on": true,
        "pre_annotation": [
            "projects/multilingual-tweet-intimacy/surveyflow/Chinese/intro.jsonl",
            "projects/multilingual-tweet-intimacy/surveyflow/Chinese/consent.jsonl",
            "projects/multilingual-tweet-intimacy/surveyflow/Chinese/instruction.jsonl"
        ],
        "post_annotation": [
            "projects/multilingual-tweet-intimacy/surveyflow/Chinese/demographic_questions.jsonl",
            "projects/multilingual-tweet-intimacy/surveyflow/Chinese/end.jsonl"
        ],
        "testing": [
            "projects/multilingual-tweet-intimacy/surveyflow/Chinese/testing.jsonl"
        ]
    },
    "automatic_assignment": {
        "on": true,
        "output_filename": "task_assignment.json",
        "sampling_strategy:": "random",
        "labels_per_instance": 10,
        "instance_per_annotator": 5,
        "test_question_per_annotator": 2,
        "users": []
    },
    "alert_time_each_instance": 10000000,
    "horizontal_key_bindings": true,
    "annotation_schemes": [
        {
            "annotation_type": "likert",
            "id": "intimacy_likert",
            "name": "\u4f60\u89c9\u5f97\u8fd9\u4e00\u6761\u63a8\u7279\u6709\u591a\u4eb2\u5bc6?",
            "description": "\u4f60\u89c9\u5f97\u8fd9\u4e00\u6761\u63a8\u7279\u6709\u591a\u4eb2\u5bc6?",
            "horizontal": true,
            "min_label": "\u5b8c\u5168\u4e0d\u4eb2\u5bc6",
            "max_label": "\u975e\u5e38\u4eb2\u5bc6",
            "size": 5,
            "displaying_score": true,
            "label_requirement": {
                "required": true
            },
            "sequential_key_binding": true
        }
    ],
    "html_layout": "templates/examples/fixed_keybinding_layout.html",
    "base_html_template": "templates/base_template.html",
    "header_file": "templates/header.html",
    "site_dir": "potato/templates/"
}